#include "../include/config_0250.h"
#include "boot_linux.h"

__attribute__((section(".entry_point"), naked, used)) void main(void) {
  __asm__ volatile(
      "cli\n"
      "cld\n"
      "movabs $0xc1010104, %rax\n"
      "movl $0x44, (%rax)\n"
      "mov $1, %eax\n"
      "cpuid\n"
      "shr $24, %ebx\n"
      "and $0xff, %ebx\n"
      "cmp $16, %ebx\n"
      "jb 1f\n"
      "0: hlt\n"
      "jmp 0b\n"
      "1:\n"
      "movabs $0xc1010104, %rax\n"
      "movl $0x45, (%rax)\n"
      "mov %ebx, %edi\n"
      "movabs $0x110000000, %rsp\n"
      "shl $12, %rbx\n"
      "add %rbx, %rsp\n"
      "mov %rsp, %rbp\n"
      "mov $0x18, %eax\n"
      "mov %ax, %ds\n"
      "mov %ax, %es\n"
      "mov %ax, %ss\n"
      "xor %eax, %eax\n"
      "mov %ax, %fs\n"
      "mov %ax, %gs\n"
      "movabs $0xc1010104, %rax\n"
      "movl $0x46, (%rax)\n"
      "call entry\n"
      "ud2\n");
}
